### ISSUE TITLE
Escape Passwords correctly!

### ISSUE THREAD

**Issue by RobinRSchulz** [kit-sdq/programming-lecture-eclipse-artemis-grading#101]
ar"Tem\155 ==> ar\"Tem\\155

**Comment by dfuchss** [comment]
I'd recommend to simply resolve the todo :) 

https://github.com/kit-sdq/programming-lecture-eclipse-artemis-grading/blob/dev/bundles/edu.kit.kastel.sdq.eclipse.grading.client/src/edu/kit/kastel/sdq/eclipse/grading/client/rest/ArtemisRESTClient.java#L160

Afterwards, you could delete the getEscapedPasswordMethod :)

https://github.com/kit-sdq/programming-lecture-eclipse-artemis-grading/commit/16dd6a03889aacf6ec31040108d1484f89b7b84b
