### ISSUE TITLE
Tooltips Mistake Preview

### ISSUE THREAD

**Issue by majuwa** [kit-sdq/programming-lecture-eclipse-artemis-grading#117]
By hoovering over one button, the tooltip should also show the text description of the mistake, not just the number of required appearances. See image for current state
![image_hoover](https://user-images.githubusercontent.com/2059629/135634108-648b0581-eec5-4db7-858c-b617963f596f.png)
.

**Comment by dfuchss** [comment]
Done in 2de1891f3ca4b7ed51e617d74cf874359d4cc3e1
