### ISSUE TITLE
Align Java-Version in Plugins

### ISSUE THREAD

**Issue by majuwa** [kit-sdq/programming-lecture-eclipse-artemis-grading#60]
Currently some plugin such as the gui use a different java version then other plugin such as the api plugin. It would be better to align these. Probably the best option would be to use java 11 as the build process unless newer java features are used. In that case all items should be changed to the newer version.

**Comment by dfuchss** [comment]
Should be resolved after merging my feature/build branch :) 

https://github.com/kit-sdq/programming-lecture-eclipse-artemis-grading/tree/feature/build

**Comment by dfuchss** [comment]
I've merged #63
