### ISSUE TITLE
Re-Check Egit clone operation

### ISSUE THREAD

**Issue by RobinRSchulz** [kit-sdq/programming-lecture-eclipse-artemis-grading#79]
"Ggf einfach schauen, was die CloneOperation macht und die entsprechenden Calls absetzen (https://git.eclipse.org/c/egit/egit.git/tree/org.eclipse.egit.core/src/org/eclipse/egit/core/op/CloneOperation.java#n139)

Da verwendet ihr dann nur objekte, die ihr laut api verwenden sollt."

**Comment by dfuchss** [comment]
Resolve or Future Work @RobinRSchulz
