### ISSUE TITLE
Code Review: Deserialization Refactoring

### ISSUE THREAD

**Issue by RobinRSchulz** [kit-sdq/programming-lecture-eclipse-artemis-grading#93]
- [ ] LockResult getMaxPoints => eher nach IExcersise
- [x] IFeedback: ggf weniger string mehr object bzw nur das verwenden was wir brauchen?
- [x] ExerciseDummy ? keine IExcersise + Participation Dummy
- [x] lockstuff vs. mappings sehr ähnlich => alles später DTOs (Data Transfer Objects)
- [ ] convertRepositoryUrl => username ist im REST (repl first)
- [x] parseAssessorResult / parser ? warum so ?
- [x] Kaskaden bei Aufbauen?
- [ ] Assessor & Co. mehrfach implemeniert? (Core)
- [x] package name "lockstuff"

**Comment by dfuchss** [comment]
Resolved ? @RobinRSchulz

**Comment by dfuchss** [comment]
Refactored code.
